DROP TRIGGER IF EXISTS on_game_finished ON games;
DROP FUNCTION IF EXISTS increment_games_played();
DROP TABLE IF EXISTS rooms CASCADE;
DROP TABLE IF EXISTS moves CASCADE;
DROP TABLE IF EXISTS games CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;
